namespace pm.Application.DTOs.Invoices;

public record InvoiceResponse(
    Guid Id,
    Guid UserId,
    Guid ClientId,
    Guid? ProjectId,
    string InvoiceNumber,
    string Status,
    string LanguageCode,
    DateOnly IssueDate,
    DateOnly DueDate,
    DateTime? SentAt,
    string Currency,
    decimal SubtotalAmount,
    decimal VatAmount,
    decimal TotalAmount,
    decimal AmountPaid,
    decimal AmountDue,
    string? PaymentLinkUrl,
    string PaymentLinkStatus,
    DateTime? PaymentLinkGeneratedAt,
    DateTime? PaymentLinkDeactivatedAt,
    string? PaymentLinkError,
    bool HasPdf,
    DateTime? PdfGeneratedAt,
    string? EmailSendStatus,
    DateTime? EmailSentAt,
    string? EmailLastError,
    string? ReminderSendStatus,
    DateTime? ReminderLastSentAt,
    int ReminderCount,
    string? ReminderLastError,
    string? Notes,
    List<LineItemResponse> LineItems,
    DateTime CreatedAt,
    DateTime UpdatedAt
);
